# Generated by Django 3.2.6 on 2021-11-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=30)),
                ('image_one', models.ImageField(upload_to='')),
                ('image_two', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
