# Generated by Django 3.2.6 on 2021-11-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mubApp', '0002_auto_20211113_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='function was nice'),
        ),
    ]
