# Generated by Django 3.2.6 on 2021-11-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mubApp', '0006_trustmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
