# Generated by Django 3.2.6 on 2021-11-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mubApp', '0008_auto_20211114_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrimonial',
            old_name='bio_data',
            new_name='upload_bio_data',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='upload_resume',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
