# Generated by Django 3.2.6 on 2021-11-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mubApp', '0010_auto_20211116_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
