# Generated by Django 3.2.6 on 2021-11-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mubApp', '0016_auto_20211125_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image_one',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_two',
        ),
        migrations.AddField(
            model_name='event',
            name='event_photos',
            field=models.ImageField(default=1, upload_to='event_images/'),
            preserve_default=False,
        ),
    ]
