# Generated by Django 3.2.6 on 2021-11-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mubApp', '0017_auto_20211125_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_photos',
            field=models.FileField(upload_to='event_images/'),
        ),
    ]
