# Generated by Django 3.2.6 on 2021-11-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mubApp', '0018_alter_event_event_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_photos',
        ),
        migrations.CreateModel(
            name='EventPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_photos', models.FileField(upload_to='event_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mubApp.event')),
            ],
        ),
    ]
