# Generated by Django 3.2.6 on 2021-11-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mubApp', '0019_auto_20211126_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventphotos',
            old_name='event_photos',
            new_name='event_photo',
        ),
    ]
